import type { Metadata } from "next";
import { Geist, Geist_Mono, Work_Sans, Manrope } from "next/font/google";
import "../globals.css";
import "../css/custom.css"


const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

const manRope = Manrope({
  variable: "--font-man-rope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable} ${manRope.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
